### ISSUE TITLE
プレゼン動画作成

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#24]
# 対応内容
- 三分以内のプレゼンを作成

## 話す内容
- Jin
  - hello everyone
  - im here to talk about our vision for the future of blockchain
- who we are
  - we are a group of skilled engineer from 42, who completed foundational curriculum in computer science
- our team
  - our strength is our experience in building infrastructure services, like shell and HTTP server
- problem
  - our problem statement is TX UX sucks for Web2 users and victims of errors.
  - In blockchain, a transaction is permanent and cannot be modified after it has been added to the blockchain
  - this is a significant problem because It doesn’t account for human mistakes that anyone can make, which is not acceptable for the masses
  - plus, people get scammed and we can not recover thier money
  - Poor UX leads to a lack of understanding and misconceptions for blockchain.
- solution
  - We believe that the key for better ux is a secure refund system.
  - Refunds are a standard feature in Web2 services, and users have come to expect this level of security and flexibility.
  - we believe that refund system has the potential for the masses to trust blockchain-based services.
  - In a world where everyday payments and transactions occur on the blockchain, a refund process is absolutely essential for everyone
  - This will allow us to build a better user experience.
- vision
  - Using the power of technology, build an infrastructure where everyone has access to essential goods and services.
- product
  - The product we are building is called Jin.
  - Jin ensures secure and automated refund processing through smart contracts. 
  - Here is an example of how Jin works.
  - In every transaction, there are two key parties: the buyer and the seller.
  - The buyer purchases a service and makes a payment. Instead of the payment going directly to the seller, it is securely held in escrow by a smart contract.
  - During the guarantee period, which is agreed upon by both the buyer and the seller, the buyer can receive a refund.
  - Once the guarantee period ends, the seller receives the payment.
  - In this way, the entire refund process is managed through smart contracts, which means we don’t allow any third parties to be involved.
- market
  - blockchain market in 2022 is 10 billion dollars
  - it is projected to grow to 1.43 trillion dollars
  - the market for refund services could reach 14.3 billion US dollars by 2030
- roadmap
  - we plan to add new feaatures to Jin like
  - developing support for more token standards.
  - improving the management of untouched tokens during the refund period for better user experience.
  - new products that align with our vision
- call to action
  - if you are interested, please reach out. im happy to chat at anytime
- closing
  - We believe that Jin is just a begginng
  - together we are building the better future for everyone and this is just the start

**Comment by YungTatyu** [comment]
# 対応内容
- 三分以内のプレゼンを作成

## 話す内容
- Jin
  - hello everyone
  - im here to talk about our vision for the future of blockchain
- who we are
  - we are a group of skilled engineer from 42, who completed foundational curriculum in computer science
- our team
  - our strength is our experience in building infrastructure services, like shell and HTTP server
- problem
  - our problem statement is TX UX sucks for Web2 users and victims of errors.
  - In blockchain, a transaction is permanent and cannot be modified after it has been added to the blockchain
  - this is a significant problem because It doesn’t account for human mistakes that anyone can make, which is not acceptable for the masses
  - plus, people get scammed and we can not recover thier money
  - Poor UX leads to a lack of understanding and misconceptions for blockchain.
- solution
  - We believe that the key for better ux is a secure refund system.
  - Refunds are a standard feature in Web2 services, and users have come to expect this level of security and flexibility.
  - we believe that refund system has the potential for the masses to trust blockchain-based services.
  - In a world where everyday payments and transactions occur on the blockchain, a refund process is absolutely essential for everyone
  - This will allow us to build a better user experience.
- vision
  - Using the power of technology, build an infrastructure where everyone has access to essential goods and services.
- product
  - The product we are building is called Jin.
  - Jin ensures secure and automated refund processing through smart contracts. 
  - Here is an example of how Jin works. In every transaction, there are two key parties: the buyer and the seller.
  - The buyer purchases a service and makes a payment. Instead of the payment going directly to the seller, it is securely held in escrow by a smart contract.
  - Buyers can receive a refund during the guarantee period agreed upon by both the buyer and seller.
  - The seller can collect the payment after the refund period ends.
  - the entire process is managed through smart contracts, which means we don’t allow any third parties to be involved
  - so there is no risk for refund fails
- market
  - blockchain market in 2022 is 10 billion dollars
  - it is projected to grow to 1.43 trillion dollars
  - the market for refund services could reach 14.3 billion US dollars by 2030
- roadmap
  - we plan to add new feaatures to Jin like
  - developing support for more token standards.
  - improving the management of untouched tokens during the refund period for better user experience.
  - new projects that align with our vision
- call to action
  - if you are interested, please reach out. im happy to chat at anytime
- closing
  - We believe that Jin is just a begginng
  - together we are building the better future for everyone and this is just the start

**Comment by tachu2** [comment]
## take1
- Jin
  - hello everyone
  - im here to talk about our vision for the future of blockchain
- who we are
  - we are a group of skilled engineer from 42, who completed foundational curriculum in computer science
- our team
  - our strength is our experience in building infrastructure services, like shell and HTTP server
- problem
  - our problem statement is TX UX sucks for Web2 users and victims of errors.
  - In blockchain, a transaction is permanent and cannot be modified after it has been added to the blockchain
  - this is a significant problem because It doesn’t account for human mistakes that anyone can make, which is not acceptable for the masses
  - plus, people get scammed and we can not recover thier money
  - Poor UX leads to a lack of understanding and misconceptions for blockchain.
- solution
  - We believe that the key for better ux is a secure refund system.
  - Refunds are a standard feature in Web2 services, and users have come to expect this level of security and flexibility.
  - we believe that refund system has the potential for the masses to trust blockchain-based services.
  - In a world where everyday payments and transactions occur on the blockchain, a refund process is absolutely essential for everyone
  - This will allow us to build a better user experience.
- vision
  - Using the power of technology, build an infrastructure where everyone has access to essential goods and services.
- product
  - The product we are building is called Jin.
  - Jin ensures secure and automated refund processing through smart contracts. 
  - There are two parties involved in the transaction: the buyer and the seller.
  - After buyers make a payment, the funds are securely held in escrow by a smart contract.
  - Buyers can receive a refund during the guarantee period agreed upon by both the buyer and seller.
  - The seller can collect the payment after the refund period ends.
  - the entire process is managed through smart contracts, which means we don’t allow any third parties to be involved
  - so there is no risk for refund fails
- market
  - blockchain market in 2022 is 10 billion dollars
  - it is projected to grow to 1.43 trillion dollars
  - the market for refund services could reach 14.3 billion US dollars by 2030
- roadmap
  - we plan to add new feaatures to Jin like
  - developing support for more token standards.
  - improving the management of untouched tokens during the refund period for better user experience.
  - new projects that align with our vision
- call to action
  - if you are interested, please reach out. im happy to chat at anytime
- closing
  - We believe that Jin is just a begginng
  - together we are building the better future for everyone and this is just the start

**Comment by tachu2** [comment]
## Take2
- Jin
  - hello everyone
  - im here to talk about our vision for the future of blockchain
- who we are
  - we are a group of skilled engineer from 42, who completed foundational curriculum in computer science
- our team
  - our strength is our experience in building infrastructure services, like shell and HTTP server
- problem
  - our problem statement is TX UX sucks for Web2 users and victims of errors.
  - In blockchain, a transaction is permanent and cannot be modified after it has been added to the blockchain
  - this is a significant problem because It doesn’t account for human mistakes that anyone can make, which is not acceptable for the masses
  - plus, people get scammed and we can not recover thier money
  - Poor UX leads to a lack of understanding and misconceptions for blockchain.
- solution
  - We believe that the key for better ux is a secure refund system.
  - Refunds are a standard feature in Web2 services, and users have come to expect this level of security and flexibility.
  - we believe that refund system has the potential for the masses to trust blockchain-based services.
  - In a world where everyday payments and transactions occur on the blockchain, a refund process is absolutely essential for everyone
  - This will allow us to build a better user experience.
- vision
  - Using the power of technology, build an infrastructure where everyone has access to essential goods and services.
- product
  - The product we are building is called Jin.
  - Jin ensures secure and automated refund processing through smart contracts. 
  - Here is an example of how Jin works.
  - In every transaction, there are two key parties: the buyer and the seller.
  - The buyer purchases a service and makes a payment. Instead of the payment going directly to the seller, it is securely held in escrow by a smart contract.
  - During the guarantee period, which is agreed upon by both the buyer and the seller, the buyer can receive a refund.
  - Once the guarantee period ends, the seller receives the payment.
  - In this way, the entire refund process is managed through smart contracts, which means we don’t allow any third parties to be involved.
- market
  - blockchain market in 2022 is 10 billion dollars
  - it is projected to grow to 1.43 trillion dollars
  - the market for refund services could reach 14.3 billion US dollars by 2030
- roadmap
  - we plan to add new feaatures to Jin like
  - developing support for more token standards.
  - improving the management of untouched tokens during the refund period for better user experience.
  - new products that align with our vision
- call to action
  - if you are interested, please reach out. im happy to chat at anytime
- closing
  - We believe that Jin is just a begginng
  - together we are building the better future for everyone and this is just the start
